services:
  imagic:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/imagic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: imagic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d imagic" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_db_data: